#!/usr/bin/env ruby
require 'daemons'

p "Usage: ruby silicond start|restart|stop (optional args)" if ARGV[0] == 'help'
p "[#{Time.now}]: Gahhh!! Let me speak the truth again!"
Daemons.run('silicondaemon.rb')